--- 
before_install: 
  - "docker build -t sahasra/docker-react -f Dockerfile.dev ."
script: 
  - "docker run  -e CI=true sahasra/docker-react npm run test -- --coverage"
services: 
  - docker
sudo: required